server:
  port: 8002
twogis:
  key: ${TWOGIS_KEY}
  url: http://routing.api.2gis.com/routing/7.0.0/global

logging:
  level:
    root: INFO
    org.eval.moretech.twogis.route.adapter.repository: DEBUG